//
// Copyright (C) 2011 Panasonic Corporation. All Rights Reserved.
//
//**********
// File Name: nbt_movies.js
// Date: 15/02/2011
// Release Date: 16 Jan 2014
// Release version: 1.0
//**********
add_package_load_path("common_env","../nbt/pkg/pkg_common_env.js");require("common_env");var menuSelected=0;var jsons=new Array();var totalObj=4;var currentPage=1;var totalPage=0;var itemsReqd=1;var curPos=0;var tempPos=0;var isLoaded=false;var httpRequestHandle;var store=0;common_key={};common_key.set_cursor=function(sobj,cobj){var old=sobj.cursor;if(old==cobj){return;}
if(old){if(old.leave_focus){old.leave_focus(old);}
old.in_cursor=false;old.toggle_cursor=false;}
if(cobj){if(cobj.enter_focus){cobj.enter_focus(cobj);}
cobj.in_cursor=true;}
sobj.cursor=cobj;};var bottomItem=new pkg_utility.breakingNews();var logo=new pkg_utility.Logo;var noFeed=pkg_utility.noFeed;var menuBg=new pkg_utility.menuBg;var loadingMsg=new pkg_utility.loadingMsg({translate:[0,0,1],height:150,width:150,font_size:16,});pkg_utility.load_pkg=loadingMsg;function formatDate(param){try{var date=param;var split_date=date.split(",");var trimdate=split_date[(split_date.length-1)].replace(/^\s+/,'')
var trimday=split_date[1].replace(/^\s+/,'');if(trimday=="Sun"||trimday=="Mon"||trimday=="Tue"||trimday=="Wed"||trimday=="Thu"||trimday=="Fri"||trimday=="Sat"){var time=trimdate.split(" ");var split_time=time[(time.length-1)].split(":");var hour="";var min=split_time[1];var zone="";var finaldate="";if(split_time[0]>12){hour=split_time[0]-12;zone="PM";;}else{hour=split_time[0];zone="AM";}
finaldate=split_date[0]+" , "+time[1]+" "+time[0]+", "+time[2]+", "+hour+":"+min+zone;return finaldate;}else{return date;}}catch(e){return date;}}
var fullStoryTextBox=new gtextbox({visible_p:false,"color":[255,0,0,255],"width":1100,"height":1000,"margin":[0,0,10,0],"font_size":35,"translate":[200,0,10],text:""});var my=function(p){var t=fullStoryTextBox.text;t=t+'\n'+p;setf_text(fullStoryTextBox,t);}
var previousPopupBtn=new container({translate:[-930,0,0],visible_p:false,components:[new gbox({"translate":[200,20,0],color:[191,191,191,255],width:459,height:160,"visible_p":true,}),new gimage({translate:[0,21,0],width:30,height:88,margin:[0,10,0,0],src:path+"nbt/images/ico_prev_nextgrey.png",}),new gtext({translate:[149,56,0],"color":[0,0,0,255],width:200,height:88,"font_size":30,"text":"पिछली खबर"}),]});previousPopupBtn.free=function(){setf_text(this.components[2],"");this.components[1].src="";force_redraw();}
var nextPopupBtn=new container({translate:[800,0,0],visible_p:false,components:[new gbox({"translate":[-45,20,0],color:[191,191,191,255],width:459,height:160,"visible_p":true,}),new gimage({translate:[130,21,0],rotation:[180,0,0,0],width:30,height:88,margin:[0,10,0,0],src:path+"nbt/images/ico_prev_nextgrey.png",}),new gtext({translate:[-120,56,0],"color":[0,0,0,255],width:200,height:88,"font_size":30,"text":"अगली खबर"}),]});nextPopupBtn.free=function(){setf_text(this.components[2],"");this.components[1].src="";force_redraw();}
var common_out_hook=function(){for(var count=0;count<nbt_movies.components.length;count++){if(nbt_movies.components[count].free){nbt_movies.components[count].free();}}
exit_appli(0);};var maskBox1=new gbox({translate:[-960,0,0],height:900,width:110,color:[246,246,246,255],});var maskBox2=new gbox({translate:[955,0,0],height:900,width:110,color:[246,246,246,255],});var scrollObject=new createScrolObject("more data",615,950,[0,-185,0]);var scrollMainContainer=scrollObject.main_cntr;var popUpCommon=new container({});popUpCommon.create=function(){this.visible_p=false;this.components=[new gbox({color:[10,10,10,200],width:4000,height:1080,}),new gbox({"translate":[0,0,0],color:[255,255,255,255],}),new gbox({"translate":[0,350,0],color:[255,255,255,255],width:400,height:80,"visible_p":true,}),this.title=new gtextbox({"translate":[17,440,0],"height":110,"width":980,"font_size":45,"color":[62,62,62,230],"margin":[-5,0,0,0],"font_name":"F015T-bold","omitter":"...","visible_p":true,}),this.date=new gtext({"translate":[-273+80,370,0],color:[127,127,127,255],"text":"","width":400+160,height:50,align:"RIGHT","omitter":" ...","font_size":20,"visible_p":true,}),new gbox({"translate":[15,350,0],color:[127,127,127,210],width:977,height:2,align:"RIGHT","visible_p":true,}),this.newsImage=new gimage({"translate":[-321,230,1],height:210,"width":300,src:"","draw_type":INSCRIBED,"onload":function(obj,http_status,err_state){force_redraw();if(http_status==200){this.error_photo.visible_p=false;this.loadingtext.visible_p=false;}},"onerror":function(obj,http_status,err_state){this.error_photo.visible_p=true;this.loadingtext.visible_p=false;force_redraw();}}),previousPopupBtn,nextPopupBtn,this.leftheadline=new gtextbox({"translate":[-730,5,0],color:[0,0,0,255],"text":"","width":300,height:60,"omitter":" ...","font_size":23,"visible_p":true,}),this.rightheadline=new gtextbox({"translate":[732,5,0],color:[0,0,0,255],"text":"","width":300,height:60,"omitter":" ...","font_size":23,"visible_p":true,}),scrollMainContainer,this.error_photo=new gimage({"translate":[-321,230,2],"src":path+"nbt/images/no_image.png","width":800,height:200,"visible_p":false}),this.loadingtext=new gtext({"translate":[-321,230,0.6],color:[20,20,20,255],"text":"लोडिंग...","width":100,height:50,align:"CENTER","omitter":" ...","font_size":18,"visible_p":true,}),];try{this.newsImage.error_photo=this.error_photo;this.newsImage.loadingtext=this.loadingtext;}catch(e){}}
popUpCommon.create();popUpCommon.enter_focus=function(){try{common_key.set_cursor(this,this.components[1]);}catch(e){}};popUpCommon.leave_focus=function(){curPos=tempPos;common_key.set_cursor(this,twoMinCnt);};popUpCommon.free=function(){try{setf_text(this.components[3],"");setf_text(this.components[11].components[2],"");setf_text(this.components[4],"");setf_text(this.components[7],"");setf_text(this.components[8],"");setf_text(this.components[10],"");this.components[6].src="";force_redraw();}catch(e){}}
popUpCommon.key_hook=function(up_down,key){if(this.cursor&&this.cursor.key_hook&&this.cursor.key_hook(up_down,key)){force_redraw();}
switch(key){case TXK_LEFT:try{PreviousPageStory();force_redraw();}catch(e){}
break;case TXK_RIGHT:try{NextPageStory();force_redraw();}catch(e){}
break;case TXK_ENTER:try{popUpDisappear();common_key.set_cursor(nbt_movies,twoMinCnt);force_redraw();}catch(e){}
return true;break;case TXK_UP:try{scrollMainContainer.move_up();force_redraw();}catch(e){}
return true;break;case TXK_DOWN:try{scrollMainContainer.move_down();force_redraw();}catch(e){}
return true;break;case TXK_RETURN:try{popUpDisappear();common_key.set_cursor(nbt_movies,twoMinCnt);force_redraw();}catch(e){}
return true;break;default:return true;break;}
return false;}
var popUpWidth=400;var popUpHeight=400;var popUpWidthShift=50;var popUpHeightShift=50;var popUpAppear=function(param){popUpCommon.visible_p=true;if(param){if(param.translate){popUpCommon.translate=param.translate;}else{popUpCommon.translate=[0,0,0];}
popUpWidth=param.width;popUpHeight=param.height;popUpWidthShift=param.width;popUpWidthShift=Math.ceil(popUpWidthShift/8);popUpHeightShift=param.height;popUpHeightShift=Math.ceil(popUpHeightShift/8);}
popUpCommon.components[1].height=1005;popUpCommon.components[1].width=1000;common_key.set_cursor(nbt_movies,popUpCommon);force_redraw();}
var popUpDisappear=function(){popUpCommon.visible_p=false;popUpCommon.free();}
var mainMenu=[{label:"राष्ट्रीय समाचार",action:function(){try{isLoaded=false;prepare_stage('nbt_home');on_stage('nbt_home');}catch(e){setError("-7");common_key.set_cursor(nbt_movies,mainMenuCnt);}},},{label:"फिल्म खबर",action:function(obj){try{prepare_stage('nbt_movies');on_stage('nbt_movies');}catch(e){setError("-7");common_key.set_cursor(nbt_movies,mainMenuCnt);}},},{label:"भविष्यफल",action:function(){try{prepare_stage('nbt_horoscope');on_stage('nbt_horoscope');}catch(e){setError("-7");common_key.set_cursor(nbt_movies,mainMenuCnt);}}},{label:"फोटो",action:function(){try{prepare_stage('nbt_photoGallery');on_stage('nbt_photoGallery');}catch(e){setError("-7");common_key.set_cursor(nbt_movies,mainMenuCnt);}},},{label:"शरारती जोक्स",action:function(){try{prepare_stage('nbt_jokes');on_stage('nbt_jokes');}catch(e){setError("-7");common_key.set_cursor(nbt_movies,mainMenuCnt);}},},];var mainMenuCnt=new container({translate:[-324,360,0],});mainMenuCnt.create=function(){if(this.components.length>0)
return;var xaxis=-140;var prevWidth=0;for(var count=0;count<mainMenu.length;count++){var tempWidth=290;xaxis=-400+count*360;if(count==menuSelected){this.components.push(new pkg_utility.menuItem({index:count,translate:[xaxis,0,0],width:tempWidth,src:path+"nbt/images/bg_selcted_tab_352x65.png",color:255,},menuSelected));}else{this.components.push(new pkg_utility.menuItem({index:count,translate:[xaxis,0,0],width:tempWidth,src:path+"nbt/images/blue_default_tab_352x65.png",},menuSelected));}
prevWidth=tempWidth;}}
mainMenuCnt.set_data=function(){for(var count=0;count<mainMenu.length;count++){this.components[count].set_data(mainMenu[count]);}}
mainMenuCnt.appear=function(){this.create();this.set_data();}
mainMenuCnt.enter_focus=function(){curPos=0;common_key.set_cursor(this,this.components[menuSelected]);}
mainMenuCnt.leave_focus=function(){common_key.set_cursor(this,null);}
mainMenuCnt.key_hook=function(up_down,key){switch(key){case TXK_LEFT:if(this.components[this.cursor.index-1]){common_key.set_cursor(this,this.components[this.cursor.index-1]);return true;}else{if(this.components[this.components.length-1]){common_key.set_cursor(this,this.components[this.components.length-1]);return true;}}
break;case TXK_RIGHT:if(this.components[this.cursor.index+1]){common_key.set_cursor(this,this.components[this.cursor.index+1]);return true;}else{if(this.components[0]){common_key.set_cursor(this,this.components[0]);return true;}}
break;case TXK_DOWN:if(isLoaded)
common_key.set_cursor(nbt_movies,twoMinCnt);return true;break;case TXK_ENTER:if(menuSelected!=this.cursor.index){delete_timer(nbt_movies);this.cursor.action();return true;}
break;case TXK_HOME:case TXK_RETURN:common_out_hook();break;}
return false;}
var twoMinCnt=new container({translate:[-458,175,0]});twoMinCnt.create=function(length,animPosition){twoMinCnt.translate[0]=2000;if(this.components.length>0){var t_len=this.components.length;this.components.splice(0,t_len);}
var ROWS=2;var COLS=2;var len;var COL_GAP=918;var ROW_GAP=-380;var x=-2;var y=-45;var givenlen=ROWS*COLS;var len=0;if(length>givenlen){len=givenlen;}else{len=length;}
for(var count=0;count<len;count++){this.components.push(new pkg_utility.TwoMinContainer({index:count,translate:[x,y,0],width:800}));x+=COL_GAP;if(0==(count+1)%COLS){x=-2;y+=ROW_GAP;}}
if("right"==animPosition){if(twoMinCnt.translate[0]>0){append_timer(nbt_movies,5,function(obj,count){twoMinCnt.translate[0]-=20;if(400==twoMinCnt.translate[0])
twoMinCnt.visible_p=true;force_redraw();if(twoMinCnt.translate[0]<=-458){delete_timer(obj);isLoaded=true;common_key.set_cursor(nbt_movies,twoMinCnt);}});}}else if("left"==animPosition){twoMinCnt.translate[0]=-2000;if(twoMinCnt.translate[0]<0){append_timer(nbt_movies,5,function(obj,count){twoMinCnt.translate[0]+=20;force_redraw();if(twoMinCnt.translate[0]>=-478){delete_timer(obj);isLoaded=true;common_key.set_cursor(nbt_movies,twoMinCnt);}});}}}
twoMinCnt.set_data=function(param){for(var count=0;count<this.components.length;count++){this.components[count].set_data(param[((currentPage-1)*4)+count]);}}
twoMinCnt.free=function(param){for(var count=0;count<this.components.length;count++){this.components[count].free();}}
twoMinCnt.appear=function(length,param,animPosition){try{this.create(length,animPosition);this.set_data(param);}catch(e){}}
twoMinCnt.enter_focus=function(){try{if(isLoaded){pkg_utility.focus.setSize(460,175);common_key.set_cursor(this,this.components[curPos]);}
force_redraw();}catch(e){}}
twoMinCnt.leave_focus=function(){common_key.set_cursor(this,null);}
twoMinCnt.key_hook=function(up_down,key){switch(key){case TXK_LEFT:if(currentPage!=1)
pkg_utility.focus.visible_p=false;if(this.components[this.cursor.index-1]){if(1==this.cursor.index%2){common_key.set_cursor(this,this.components[this.cursor.index-1]);return true;}else{PreviousPage();return true;}}else{PreviousPage();return true;}
break;case TXK_RIGHT:if(currentPage!=totalPage)
pkg_utility.focus.visible_p=false;if(this.components[this.cursor.index+1]){if(0==this.cursor.index%2){common_key.set_cursor(this,this.components[this.cursor.index+1]);return true;}else{NextPage();return true;}}else{NextPage();return true;}
break;case TXK_UP:if(this.components[this.cursor.index-2]){common_key.set_cursor(this,this.components[this.cursor.index-2]);return true;}else{common_key.set_cursor(nbt_movies,mainMenuCnt);return true;}
break;case TXK_DOWN:if(this.components[this.cursor.index+2]){common_key.set_cursor(this,this.components[this.cursor.index+2]);return true;}else{common_key.set_cursor(nbt_movies,mainMenuCnt);return true;}
break;case TXK_EXIT:return false;break;case TXK_ENTER:try{tempPos=this.cursor.index;var tempValue=((currentPage-1)*4)+this.cursor.index;PopupDetails(tempValue);}catch(e){}
break;case TXK_HOME:case TXK_RETURN:common_out_hook();}
return false;}
var previousBtn=new container({translate:[-930,-40,0],visible_p:false,components:[new gimage({translate:[0,-18,0],width:30,height:88,margin:[0,10,0,0],src:path+"nbt/images/ico_prev_next.png",}),]});var nextBtn=new container({translate:[1006,-40,0],rotation:[180,0,0,0],visible_p:false,components:[new gimage({translate:[80,15,0],width:30,height:88,color:[255,255,255,255],margin:[0,10,0,0],src:path+"nbt/images/ico_prev_next.png",}),]});var pageInfo=new container({translate:[650,-465,0],components:[new gtext({translate:[95,0,0],width:80,color:[0,0,0,255],margin:[0,10,0,0],text:"पेज","align":RIGHT,"visible_p":false,}),new gtext({translate:[100,0,0],width:250,color:[0,0,0,255],margin:[0,10,0,0],"align":RIGHT,}),]});var initiateStage=function(){pkg_utility.focus.rebuild("small");noFeed.visible_p=false;mainMenuCnt.appear();getTwoMinNews("right");common_key.set_cursor(this,mainMenuCnt);};var nbt_movies=stage({"symbol":"nbt_movies","bg_image":[pkg_utility.stageBg,],"in":[{"from":["default"],"hook":function(obj){menuSelected=1;pkg_utility.selectedMenu=menuSelected;currentPage=1;if(httpRequestHandle){cancel_http_request(httpRequestHandle);httpRequestHandle=null;}
complete_on_stage(obj);loadingMsg.on();initiateStage();}},],"out":[{"to":["default"],"hook":function(obj){complete_off_stage(obj);if(httpRequestHandle){cancel_http_request(httpRequestHandle);httpRequestHandle=null;}
discard_stage("nbt_movies");}}],"components":[menuBg,logo,mainMenuCnt,twoMinCnt,maskBox1,maskBox2,previousBtn,nextBtn,pageInfo,bottomItem,noFeed,popUpCommon,pkg_utility.focus,loadingMsg,fullStoryTextBox],});nbt_movies.key_hook=function(up_down,key){if(up_down!=KEY_PRESS){return false;}
if(this.cursor&&this.cursor.key_hook&&this.cursor.key_hook(up_down,key)){force_redraw();}
if(key==TXK_HOME){if(!pkg_utility.is_easy_IPTV()){exit_appli(0);}else{return false;}}
return false;}
var PreviousPage=function(){if(1==currentPage){return;}else{twoMinCnt.free();curPos=0;currentPage-=1;getTwoMinNews("left");popupClosed=false;pkg_utility.focus.moveTo(-460,170);}
common_key.set_cursor(this,this.components[0]);}
var NextPage=function(){if(totalPage==currentPage){return;}else{twoMinCnt.free();curPos=0;currentPage+=1;getTwoMinNews("right");popupClosed=false;pkg_utility.focus.moveTo(-460,170);}
common_key.set_cursor(this,this.components[0]);}
var PreviousPageStory=function(){var totalLength=jsons.length-1;if(0==store){return;}else{if(store>=1){popUpCommon.free();store-=1;PopupDetails(store);popUpenableNavigation();}}}
var NextPageStory=function(){var totalLength=jsons.length-1;if((totalLength)==(store)){return;}else{if(store<(totalLength)){popUpCommon.free();store+=1;PopupDetails(store);popUpenableNavigation();}}}
var popUpenableNavigation=function(){try{var totalLength=jsons.length-1;if(store>0){var prevHeadline=jsons[store-1].HeadLine;if(prevHeadline.length>50){prevHeadline=prevHeadline.substring(0,50)+"...";setf_text(popUpCommon.components[9],prevHeadline);}else{prevHeadline;setf_text(popUpCommon.components[9],prevHeadline);}}
var nextHeadline=jsons[store+1].HeadLine;if(nextHeadline.length>50){nextHeadline=nextHeadline.substring(0,50)+"...";setf_text(popUpCommon.components[10],nextHeadline);}else{nextHeadline;setf_text(popUpCommon.components[10],nextHeadline);}
if((1==store)&&(store==totalLength)){setf_text(popUpCommon.components[9],prevHeadline);setf_text(popUpCommon.components[10],nextHeadline);nextPopupBtn.visible_p=false;previousPopupBtn.visible_p=false;}else if(0==store){setf_text(popUpCommon.components[9],"");setf_text(popUpCommon.components[10],nextHeadline);nextPopupBtn.visible_p=true;previousPopupBtn.visible_p=false;}else if((store)==(totalLength)){setf_text(popUpCommon.components[9],prevHeadline);setf_text(popUpCommon.components[10],"");nextPopupBtn.visible_p=false;previousPopupBtn.visible_p=true;}else{setf_text(popUpCommon.components[9],prevHeadline);setf_text(popUpCommon.components[10],nextHeadline);nextPopupBtn.visible_p=true;previousPopupBtn.visible_p=true;}}catch(e){nextPopupBtn.visible_p=false;previousPopupBtn.visible_p=true;}}
var enableNavigation=function(){if((1==currentPage)&&(currentPage==totalPage)){nextBtn.visible_p=false;previousBtn.visible_p=false;}else if(1==currentPage){nextBtn.visible_p=true;previousBtn.visible_p=false;}else if(currentPage==totalPage){nextBtn.visible_p=false;previousBtn.visible_p=true;}else{nextBtn.visible_p=true;previousBtn.visible_p=true;}}
var displayPageInfo=function(){pageInfo.components[0].visible_p=true;if((currentPage>=1)&&(currentPage<=9))
pageInfo.components[0].translate[0]=115;if((currentPage>=10)&&(currentPage<=99))
pageInfo.components[0].translate[0]=100;force_redraw();setf_text(pageInfo.components[1],currentPage+"/"+totalPage);}
var setError=function(param){var errTxtMsg="";switch(param){case"onLoad":errTxtMsg="Network connection failure !";break;case-7:errTxtMsg="नेटवर्क कनेक्शन की विफलता";break;case-6:errTxtMsg="नेटवर्क कनेक्शन की विफलता";break;case-28:errTxtMsg="अनुरोध समय समाप्त";break;case 403:errTxtMsg="अस्वीकृत किया गया";break;case 404:errTxtMsg="डेटा उपलब्ध नहीं है।";break;case 500:errTxtMsg="आंतरिक सर्वर समस्या";break;default:errTxtMsg="फिलहाल डेटा उपलब्ध नहीं है ।";break;}
setf_text(noFeed,errTxtMsg);common_key.set_cursor(nbt_movies,mainMenuCnt);};var getTwoMinNews=function(animPosition){noFeed.visible_p=false;if(jsons.length<=0){if(httpRequestHandle){cancel_http_request(httpRequestHandle);httpRequestHandle=null;}
httpRequestHandle=http_request({url:"http://navbharattimes.indiatimes.com/newslisting/2303550.cms?stryfmt=1&stryno=20&feedtype=simplejson&source=panasonic",method:"GET",onload:function(status,header,body){if(200==status){try{var verifiedData=pkg_utility.verifyJsonData(body);noFeed.visible_p=false;var twoMinObj=eval("("+verifiedData+")");var total=twoMinObj.NewsItem.length;var total1=twoMinObj.NewsItem[0].HeadLine;totalPage=parseInt(total/totalObj)+((total%totalObj)==0?0:1);for(var i=0;i<total;i++){jsons.push(twoMinObj.NewsItem[i]);}
itemsReqd=(totalPage==currentPage)?((total==totalObj)?totalObj:(total%totalObj)):totalObj;displayPageInfo();loadingMsg.off();twoMinCnt.appear(itemsReqd,jsons,animPosition);enableNavigation();}catch(err){setError(status);noFeed.visible_p=true;loadingMsg.off();common_key.set_cursor(nbt_movies,mainMenuCnt);}}else{setError(status);noFeed.visible_p=true;loadingMsg.off();}},sync:false,});}else{total=jsons.length;totalPage=parseInt(total/totalObj)+((total%totalObj)==0?0:1);itemsReqd=(totalPage==currentPage)?(total%totalObj):totalObj;displayPageInfo();if(0==itemsReqd){itemsReqd=4;}
twoMinCnt.appear(itemsReqd,jsons,animPosition);enableNavigation();common_key.set_cursor(nbt_movies,twoMinCnt);}}
var data_font_color=[74,74,74,150];var data_cuisine_font_color=[62,62,64,255];var data_affordable_color=[62,62,62,255];var data_name_color=[74,74,74,255];var data_small_font_color=[81,81,81,200];var data_head_color=[73,73,73,150];function createScrolObject(source_text,scroll_height,scroll_width,scroll_position){this.topMask=new gbox({translate:[0,(1080/2)+Math.ceil(scroll_height/2)-4,0.1],rotation:[0,0,0,0],color:[22,22,22,0],width:scroll_width,height:1080,visible_p:true,});this.textBox=new gtextbox({translate:[0,(-1)*(Math.ceil(66*72/2)-Math.ceil(scroll_height/2)),0],color:[127,127,127,255],width:scroll_width,height:66*72,text:source_text,align:LEFT,font_size:30,visible_p:true,"font_size":32,omitter:"...",});this.scrollArea=new gbox({translate:[Math.ceil(scroll_width/2)+15+23,185,0],rotation:[0,0,0,0],color:[205,205,205,255],width:25,height:1005,visible_p:true,});this.upScroll=new gbox({translate:[Math.ceil(scroll_width/2)+15+23,Math.floor(scroll_height/2)-12,0],rotation:[0,0,0,0],color:[22,22,22,111],width:25,height:25,visible_p:false,});this.downScroll=new gbox({translate:[Math.ceil(scroll_width/2)+15+23,(-1)*(Math.floor(scroll_height/2)-12),0],rotation:[0,0,0,0],color:[22,22,22,111],width:25,height:25,visible_p:false,});this.scrollableBox=new actor({translate:[Math.ceil(scroll_width/2)+15+23,185,0],rotation:[0,0,0,0],base_col_width:0,cursor_width:0,bg_image:[new gbox({translate:[0,0,0],rotation:[0,0,0,0],color:[127,127,127,255],width:24,height:1000,visible_p:true,round_enable:true,round_width:8,round_height:8,round_level:16,}),],visible_p:true,});this.buttonMask=new gbox({translate:[0,(-1)*((1080/2)+Math.ceil(scroll_height/2)),0.1],rotation:[0,0,0,0],color:[22,22,22,0],width:scroll_width,height:1080,visible_p:true,});this.main_cntr=new container({translate:scroll_position,visible_p:true,components:[this.topMask,this.buttonMask,this.textBox,this.scrollArea,this.upScroll,this.downScroll,this.scrollableBox,],});this.main_cntr.enter_focus=function(){common_key.set_cursor(this,this.components[7]);force_redraw();};this.main_cntr.leave_focus=function(){common_key.set_cursor(this,null);};var source_text_proporty=get_dimension_textbox(this.textBox);this.source_text_height=source_text_proporty[1]-5;var each_row_height=get_text_font_height(this.textBox,"ि");this.extra_height=this.source_text_height-scroll_height;this.max_scrolable_height=1000;(scroll_height);var total_no_of_move=0;var curent_no_move=0;var each_move_height=0;var scrolbar_visible=false;if(this.extra_height>0){total_no_of_move=Math.ceil(this.extra_height/each_row_height);if(total_no_of_move==1){this.scrollableBox.bg_image[0].height=Math.ceil(this.max_scrolable_height-30);}else if(total_no_of_move==2){this.scrollableBox.bg_image[0].height=Math.ceil(this.max_scrolable_height-60);}else{this.scrollableBox.bg_image[0].height=2*Math.ceil(this.max_scrolable_height/total_no_of_move);}
this.abailabe_scrolable_height=this.max_scrolable_height-this.scrollableBox.bg_image[0].height;each_move_height=Math.floor(this.abailabe_scrolable_height/total_no_of_move);this.scrollableBox.translate[1]=185+(this.max_scrolable_height/2)-Math.floor(this.scrollableBox.bg_image[0].height/2);scrolbar_visible=true;this.scrollArea.visible_p=true;this.upScroll.visible_p=false;this.downScroll.visible_p=false;this.scrollableBox.visible_p=true;}else{scrolbar_visible=false;this.scrollArea.visible_p=false;this.upScroll.visible_p=false;this.downScroll.visible_p=false;this.scrollableBox.visible_p=false;};this.main_cntr.move_up=function(){if(curent_no_move<=0){return false;}
this.components[6].translate[1]+=each_move_height;this.components[2].translate[1]-=each_row_height;curent_no_move--;force_redraw();return true;};this.main_cntr.move_down=function(){if(curent_no_move>=total_no_of_move){return false;}
this.components[6].translate[1]-=each_move_height
this.components[2].translate[1]+=each_row_height;curent_no_move++;force_redraw();return true;};this.reposition=function(){curent_no_move=0;this.textBox.translate[1]=(-1)*(Math.ceil(66*72/2)-Math.ceil(scroll_height/2));this.scrollableBox.translate[1]=185+(this.max_scrolable_height/2)-Math.floor(this.scrollableBox.bg_image[0].height/2);force_redraw();return true;}
this.resetText=function(scrollText){setf_text(this.textBox,scrollText);source_text_proporty=get_dimension_textbox(this.textBox);this.source_text_height=source_text_proporty[1]-5;each_row_height=get_text_font_height(this.textBox,"ि");this.extra_height=this.source_text_height-scroll_height;this.max_scrolable_height=1000;total_no_of_move=0;curent_no_move=0;each_move_height=0;scrolbar_visible=false;if(this.extra_height>0){total_no_of_move=Math.ceil(this.extra_height/each_row_height);if(total_no_of_move>62)
total_no_of_move=62;if(total_no_of_move==1){this.scrollableBox.bg_image[0].height=Math.ceil(this.max_scrolable_height-30);}else if(total_no_of_move==2){this.scrollableBox.bg_image[0].height=Math.ceil(this.max_scrolable_height-60);}else{this.scrollableBox.bg_image[0].height=2*Math.ceil(this.max_scrolable_height/total_no_of_move);}
this.abailabe_scrolable_height=this.max_scrolable_height-this.scrollableBox.bg_image[0].height;each_move_height=Math.floor(this.abailabe_scrolable_height/total_no_of_move);this.scrollableBox.translate[1]=185+(this.max_scrolable_height/2)-Math.floor(this.scrollableBox.bg_image[0].height/2);scrolbar_visible=true;this.scrollArea.visible_p=true;nextPopupBtn.components[0].width=459;this.upScroll.visible_p=false;this.downScroll.visible_p=false;this.scrollableBox.visible_p=true;}else{scrolbar_visible=false;nextPopupBtn.components[0].width=459;this.scrollArea.visible_p=true;this.upScroll.visible_p=false;this.downScroll.visible_p=false;this.scrollableBox.visible_p=false;}
curent_no_move=0;this.textBox.translate[1]=(-1)*(Math.ceil(66*72/2)-Math.ceil(scroll_height/2));this.scrollableBox.translate[1]=185+(this.max_scrolable_height/2)-Math.floor(this.scrollableBox.bg_image[0].height/2);force_redraw();return true;};};var PopupDetails=function(param){var twoMinImage="";var selectedIndex=param;store=selectedIndex;popUpenableNavigation();var properData=jsons[selectedIndex].HeadLine;if(properData.length>200){setf_text(popUpCommon.components[3],properData.substring(0,90)+"...");}else{setf_text(popUpCommon.components[3],properData);}
var date="";date=formatDate(jsons[selectedIndex].DateLine);setf_text(popUpCommon.components[4],date);var str=jsons[selectedIndex].Photo;try{if(jsons[selectedIndex].Photo){twoMinImage=jsons[selectedIndex].Photo;popUpCommon.components[12].visible_p=false;popUpCommon.components[6].src=twoMinImage;}else{popUpCommon.components[6].src="";popUpCommon.components[12].visible_p=true;}}catch(e){}
if(!twoMinImage==undefined)
popUpCommon.components[6].src=twoMinImage;var bodyData=jsons[selectedIndex].Story;if(bodyData==undefined){bodyData="समाचार उपलब्ध नहीं है ।";scrollObject.resetText(bodyData);force_redraw();}else{bodyData=bodyData.replace(/\n \n/gi,"\n\n");bodyData=bodyData.replace(/\n\n/gi,"\n");bodyData=bodyData.replace(/\n\n\n\n/gi,"\n");scrollObject.resetText(bodyData);}
pkg_utility.focus.visible_p=false;force_redraw();popUpAppear({width:1000,height:986,translate:[0,0,0],});return true;}
ready_appli();